const DB={authSettings:"tms_auth_settings",pujas:"tms_pujas",events:"tms_events",gallery:"tms_gallery",bookings:"tms_bookings",donations:"tms_donations",users:"tms_users",messages:"tms_messages",contactSettings:"tms_contact_settings",developerSettings:"tms_developer_settings",socialSettings:"tms_social_settings",noticeSettings:"tms_notice_settings",homeSettings:"tms_home_settings",aboutSettings:"tms_about_settings",aboutImages:"tms_about_images",aboutVault:"tms_about_vault",aboutActivities:"tms_about_activities"};function getData(k){return JSON.parse(localStorage.getItem(DB[k])||"[]")}function saveData(k,v){localStorage.setItem(DB[k],JSON.stringify(v))}function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
const defaults={pujas:[{id:"p1",name:"Morning Puja",time:"06:00 AM",description:"Morning prayer and deity worship."},{id:"p2",name:"Madhyahna Bhog",time:"12:00 PM",description:"Midday bhog offering."},{id:"p3",name:"Evening Aarti",time:"07:00 PM",description:"Evening aarti and devotional prayer."}],events:[{id:"e1",name:"Special Puja",date:"15 October 2026",description:"Special devotional puja."},{id:"e2",name:"Temple Festival",date:"25 October 2026",description:"Temple festival and cultural program."}],gallery:[{id:"g1",title:"Temple",image:"https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=900&q=80"},{id:"g2",title:"Devotion",image:"https://images.unsplash.com/photo-1604608672516-f1b9e5d8b9c8?auto=format&fit=crop&w=900&q=80"}]};
Object.keys(defaults).forEach(k=>{if(!localStorage.getItem(DB[k]))saveData(k,defaults[k])});
if(!localStorage.getItem(DB.aboutSettings)) saveData('aboutSettings',[{bannerEyebrow:'OUR JOURNEY',bannerTitle:'About Divine Temple',bannerDescription:'A spiritual home built around devotion, service and harmony.',introEyebrow:'OUR TEMPLE',introTitle:'A Sacred Space for Everyone',introText:'Divine Temple is a place where devotees come together for prayer, puja, festivals and community service. Our goal is to create a peaceful environment where every visitor can feel connected to faith and community.\n\nFrom daily aarti to special celebrations, the temple provides opportunities for worship, learning and meaningful participation throughout the year.',valuesTitle:'What We Stand For',ctaTitle:'Be Part of the Divine Community',ctaDescription:'Join us for worship, celebration and service.'}]);
if(!localStorage.getItem(DB.aboutImages)) saveData('aboutImages',[]);
if(!localStorage.getItem(DB.aboutVault)) saveData('aboutVault',[]);
if(!localStorage.getItem(DB.aboutActivities)) saveData('aboutActivities',[{id:'a1',icon:'01',title:'Daily Puja & Aarti',description:'Begin and end the day with regular worship and devotional practices.'},{id:'a2',icon:'02',title:'Special Puja & Festivals',description:'Participate in special occasions, festivals and cultural programs.'},{id:'a3',icon:'03',title:'Bookings & Donations',description:'Use the online system to submit puja bookings and support temple activities.'}]);
const defaultContact={address:"Sahania, Keshrambha, Dantan, Paschim Medinipur, 721451",phone:"9332716479",email:"maitysachin591@gmail.com",location:"Sahania, Keshrambha, Dantan, Paschim Medinipur, 721451"};
if(!localStorage.getItem(DB.contactSettings)) saveData("contactSettings",defaultContact);
if(!localStorage.getItem(DB.socialSettings)) saveData("socialSettings",[{facebook:"",youtube:"",instagram:""}]);
if(!localStorage.getItem(DB.noticeSettings)) saveData("noticeSettings",[]);
if(!localStorage.getItem(DB.homeSettings)) saveData("homeSettings",[{eyebrow:"🙏 WELCOME TO DIVINE TEMPLE",heading:"A Place of",highlight:"Faith, Peace & Devotion",description:"Experience daily worship, sacred celebrations and community service — all in one place.",heroImage:"",primaryText:"🪔 Book a Puja",primaryLink:"booking.html",secondaryText:"Explore Temple",secondaryLink:"about.html",welcomeTitle:"Everything for Your Spiritual Journey",welcomeDescription:"Stay connected with the temple, manage bookings and participate in sacred events.",ctaTitle:"Support Temple Activities",ctaDescription:"Your contribution helps us continue worship, festivals and community programs."}]);

const defaultAuthSettings={
 admin:{username:"admin",password:"admin123",phone:"9332716479"},
 developer:{username:"developer",password:"developer123",phone:"9332716479"}
};
if(!localStorage.getItem(DB.authSettings)) saveData("authSettings",defaultAuthSettings);
const defaultDeveloper={name:"Website Developer",photo:"",email:"developer@example.com"};
if(!localStorage.getItem(DB.developerSettings)) saveData("developerSettings",defaultDeveloper);
