const aboutDefaults={bannerEyebrow:'OUR JOURNEY',bannerTitle:'About Divine Temple',bannerDescription:'A spiritual home built around devotion, service and harmony.',introEyebrow:'OUR TEMPLE',introTitle:'A Sacred Space for Everyone',introText:'Divine Temple is a place where devotees come together for prayer, puja, festivals and community service. Our goal is to create a peaceful environment where every visitor can feel connected to faith and community.\n\nFrom daily aarti to special celebrations, the temple provides opportunities for worship, learning and meaningful participation throughout the year.',valuesTitle:'What We Stand For',ctaTitle:'Be Part of the Divine Community',ctaDescription:'Join us for worship, celebration and service.'};
function arr(k){return getData(k)}
function saveArr(k,v){saveData(k,v);renderAll()}
async function readImage(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{const s=Math.min(1,1400/Math.max(img.width,img.height));const c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*s));c.height=Math.max(1,Math.round(img.height*s));c.getContext('2d').drawImage(img,0,0,c.width,c.height);res(c.toDataURL('image/jpeg',.82));};img.onerror=rej;img.src=r.result};r.onerror=rej;r.readAsDataURL(file)})}
function renderImages(){const root=document.getElementById('aboutImagesList');const items=arr('aboutImages');root.innerHTML=items.map(x=>`<div class="admin-item"><img src="${esc(x.image)}"><strong>${esc(x.caption||'About Image')}</strong><button class="btn-danger" onclick="removeAboutImage('${x.id}')">Delete</button></div>`).join('')||'<div class="empty-state">No images added yet.</div>'}
function renderVault(){const root=document.getElementById('vaultList');const items=arr('aboutVault');root.innerHTML=items.map(x=>`<div class="admin-item"><div class="item-icon">${esc(x.icon||'✨')}</div><strong>${esc(x.title)}</strong><p>${esc(x.description)}</p><small>${esc(x.link||'No link')}</small><button class="btn-danger" onclick="removeVault('${x.id}')">Delete</button></div>`).join('')||'<div class="empty-state">No vault features added yet.</div>'}
function renderActivities(){const root=document.getElementById('activityList');const items=arr('aboutActivities');root.innerHTML=items.map(x=>`<div class="admin-item"><div class="item-number">${esc(x.icon||'01')}</div><strong>${esc(x.title)}</strong><p>${esc(x.description)}</p><button class="btn-danger" onclick="removeActivity('${x.id}')">Delete</button></div>`).join('')||'<div class="empty-state">No activities added yet.</div>'}
function renderAll(){renderImages();renderVault();renderActivities()}
window.removeAboutImage=id=>saveArr('aboutImages',arr('aboutImages').filter(x=>x.id!==id));window.removeVault=id=>saveArr('aboutVault',arr('aboutVault').filter(x=>x.id!==id));window.removeActivity=id=>saveArr('aboutActivities',arr('aboutActivities').filter(x=>x.id!==id));
document.addEventListener('DOMContentLoaded',()=>{const h=Object.assign({},aboutDefaults,getData('aboutSettings')[0]||{});Object.keys(aboutDefaults).forEach(k=>{const e=document.getElementById(k);if(e)e.value=h[k]??''});document.getElementById('aboutForm').onsubmit=e=>{e.preventDefault();const out={};Object.keys(aboutDefaults).forEach(k=>out[k]=document.getElementById(k).value.trim());saveData('aboutSettings',[out]);document.getElementById('aboutMsg').innerHTML='<span class="alert alert-success" style="display:inline-block;margin-left:10px">About content saved.</span>'};document.getElementById('addAboutImage').onclick=async()=>{let image=document.getElementById('aboutImageUrl').value.trim();const f=document.getElementById('aboutImageFile').files[0];if(f)image=await readImage(f);if(!image){alert('Add an image URL or choose an image.');return}const a=arr('aboutImages');a.push({id:uid(),image,caption:document.getElementById('aboutImageCaption').value.trim()});saveArr('aboutImages',a);document.getElementById('aboutImageUrl').value='';document.getElementById('aboutImageFile').value='';document.getElementById('aboutImageCaption').value=''};document.getElementById('addVault').onclick=()=>{const title=document.getElementById('vaultTitle').value.trim();if(!title){alert('Enter a feature title.');return}const a=arr('aboutVault');a.push({id:uid(),title,icon:document.getElementById('vaultIcon').value.trim()||'✨',description:document.getElementById('vaultDescription').value.trim(),link:document.getElementById('vaultLink').value.trim()});saveArr('aboutVault',a);['vaultTitle','vaultIcon','vaultDescription','vaultLink'].forEach(id=>document.getElementById(id).value='')};document.getElementById('addActivity').onclick=()=>{const title=document.getElementById('activityTitle').value.trim();if(!title){alert('Enter an activity title.');return}const a=arr('aboutActivities');a.push({id:uid(),title,icon:document.getElementById('activityIcon').value.trim()||String(a.length+1).padStart(2,'0'),description:document.getElementById('activityDescription').value.trim()});saveArr('aboutActivities',a);['activityTitle','activityIcon','activityDescription'].forEach(id=>document.getElementById(id).value='')};renderAll()});
